version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .