name: Test dependencies # workflow name
description: Workflow for installing test dependencies

# === install test dependencies ===
runs:
  using: composite

  steps: # tasks

    - name: Install package dependencies
      uses: ./.github/common/install_dependencies
    
    - name: Install test dependencies
      shell: bash
      run: |
        # Compile libjpeg 9e
        curl -s -L https://ijg.org/files/jpegsrc.v9e.tar.gz | tar xvz
        cd jpeg-9e
        mkdir build && ./configure --prefix=$(pwd)/build && make && make install