name: Build from source # workflow name
description: Workflow for building the library from the source

runs:
  using: composite

  steps: # tasks

    - name: Build library # build CJpegLib
      shell: bash
      run: |
        pip3 install -e .

