name: Test dependencies # workflow name
description: Workflow for installing test dependencies

# === install test dependencies ===
runs:
  using: composite

  steps: # tasks

    - name: Install package dependencies
      uses: ./.github/common/install_dependencies

    - name: Install test dependencies
      shell: bash
      run: |
        choco --help
        if [ -f tests/requirements.txt ]; then pip3 install -r tests/requirements.txt; fi
        pip3 install torchjpeg || true
        git clone https://github.com/btlorch/dct-coefficient-decoder
        cd dct-coefficient-decoder
        git checkout 8f05ed58ff95a2475defa117f9eeccdcee795dc2
        cat decoder.pyx | sed -E 's/(.*BG_RGB.*)/# \1/g' | sed -E 's/(.*BG_YCC.*)/# \1/g' > decoder.pyx
        python setup.py install || true
        cd ..
        sudo apt-get install -y libjpeg62-dev || true # default-jre-headless libjpeg62
        git clone https://github.com/dwgoon/jpegio
        cd jpegio
        sed -E 's/^.*-march=native.*$//' -i setup.py
        sed -E 's/const //' -i jpegio/clibjpeg.pxd
        python3 setup.py install || true
        cd ..
        pip3 install git+https://github.com/daniellerch/python-jpeg-toolbox@829dbb9c50d0c885d228fc087de1c104160eee33 || true
        # Compile libjpeg 9e
        curl -s -L https://ijg.org/files/jpegsrc.v9e.tar.gz | tar xvz
        cd jpeg-9e
        mkdir build && ./configure --prefix=$(pwd)/build && make && make install || true