name: Test dependencies # workflow name
description: Workflow for installing test dependencies

# === install test dependencies ===
runs:
  using: composite

  steps: # tasks

    - name: Install package dependencies
      uses: ./.github/common/install_dependencies

    - name: Install test dependencies
      shell: bash
      run: |
        if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
        pip install torchjpeg; true
        git clone https://github.com/btlorch/dct-coefficient-decoder
        cd dct-coefficient-decoder
        git checkout 8f05ed58ff95a2475defa117f9eeccdcee795dc2
        cat decoder.pyx | sed -E 's/(.*BG_RGB.*)/# \1/g' | sed -E 's/(.*BG_YCC.*)/# \1/g' > decoder.pyx
        python setup.py install
        cd ..
        sudo apt-get install -y libjpeg62-dev # default-jre-headless libjpeg62
        git clone https://github.com/dwgoon/jpegio
        cd jpegio
        cat setup.py | sed -E 's/^.*-march=native.*$//' > setup2.py
        mv setup2.py setup.py
        python3 setup.py install; true
        python3 setup.py install
        cd ..
        pip3 install git+https://github.com/daniellerch/python-jpeg-toolbox@829dbb9c50d0c885d228fc087de1c104160eee33

